version: "1.0"
services:
  db:
    container_name: "db"
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresdb
    ports:
      - "5432:5432"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge