"""Equations creation

Revision ID: 1a45a77851fe
Revises: b4e515732bd3
Create Date: 2024-04-21 14:02:42.286521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a45a77851fe'
down_revision: Union[str, None] = 'b4e515732bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('params_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['params_id'], ['params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equation_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equation_id'], ['equation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'equation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equation_user')
    op.drop_table('equation')
    op.drop_table('params')
    # ### end Alembic commands ###
